# Generated by Django 5.0.14 on 2026-08-24 00:07

import django.db.models.deletion
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("ledger", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenancyPaymentReference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(default="sandbox", max_length=32)),
                (
                    "reference",
                    models.CharField(
                        default=payments.models.generate_payment_reference,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "payid",
                    models.CharField(
                        blank=True,
                        help_text="Provider-issued virtual PayID, once registered.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "tenancy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_reference",
                        to="portfolio.tenancy",
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_references",
                        to="ledger.trustaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncomingPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("provider_txn_id", models.CharField(max_length=255)),
                ("reference", models.CharField(max_length=64)),
                ("amount_cents", models.BigIntegerField()),
                ("paid_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched and receipted"),
                            ("unmatched", "No matching tenancy reference"),
                        ],
                        max_length=16,
                    ),
                ),
                ("raw", models.JSONField(default=dict)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.receipt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organisation", "status"],
                        name="payments_in_organis_82e97b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="incomingpayment",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_txn_id"), name="uniq_incoming_payment_txn"
            ),
        ),
    ]
