# Generated by Django 5.0.14 on 2026-08-24 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("ending", "Ending"),
                            ("ended", "Ended"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Fixed-term end; blank = periodic.",
                        null=True,
                    ),
                ),
                ("rent_amount_cents", models.BigIntegerField()),
                (
                    "rent_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=16,
                    ),
                ),
                ("bond_amount_cents", models.BigIntegerField(default=0)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("bank_account_label", models.CharField(blank=True, max_length=255)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnerProperty",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("share_basis_points", models.PositiveIntegerField(default=10000)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="portfolio.owner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "owner properties",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("suburb", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NSW", "New South Wales"),
                            ("VIC", "Victoria"),
                            ("QLD", "Queensland"),
                            ("WA", "Western Australia"),
                            ("SA", "South Australia"),
                            ("TAS", "Tasmania"),
                            ("ACT", "Australian Capital Territory"),
                            ("NT", "Northern Territory"),
                        ],
                        max_length=3,
                    ),
                ),
                ("postcode", models.CharField(max_length=4)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("car_spaces", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="properties",
                        through="portfolio.OwnerProperty",
                        to="portfolio.owner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
        migrations.AddField(
            model_name="ownerproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="portfolio.property",
            ),
        ),
        migrations.CreateModel(
            name="RentSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_cents", models.BigIntegerField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("first_due_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_schedules",
                        to="portfolio.lease",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenancy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Human-readable tenancy reference, unique within the organisation.",
                        max_length=32,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancies",
                        to="portfolio.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tenancies",
            },
        ),
        migrations.CreateModel(
            name="RentCharge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_date", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("amount_cents", models.BigIntegerField()),
                ("paid_cents", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                        ],
                        default="due",
                        max_length=16,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="portfolio.rentschedule",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_charges",
                        to="portfolio.tenancy",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.AddField(
            model_name="lease",
            name="tenancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="portfolio.tenancy",
            ),
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tenancy",
            name="tenants",
            field=models.ManyToManyField(
                related_name="tenancies", to="portfolio.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(
                fields=["organisation", "name"], name="portfolio_o_organis_4781bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["organisation", "state"], name="portfolio_p_organis_609f23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["organisation", "suburb"], name="portfolio_p_organis_af1795_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerproperty",
            constraint=models.UniqueConstraint(
                fields=("owner", "property"), name="uniq_owner_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerproperty",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("share_basis_points__gt", 0), ("share_basis_points__lte", 10000)
                ),
                name="ownership_share_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentschedule",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_cents__gt", 0)), name="schedule_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="rentcharge",
            index=models.Index(
                fields=["organisation", "tenancy", "due_date"],
                name="portfolio_r_organis_492d0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentcharge",
            index=models.Index(
                condition=models.Q(("status", "paid"), _negated=True),
                fields=["organisation", "due_date"],
                name="rentcharge_unpaid_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentcharge",
            constraint=models.UniqueConstraint(
                fields=("schedule", "due_date"),
                name="uniq_charge_per_schedule_due_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentcharge",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_cents__gt", 0)), name="charge_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentcharge",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("paid_cents__gte", 0),
                    ("paid_cents__lte", models.F("amount_cents")),
                ),
                name="charge_paid_within_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["organisation", "state"], name="portfolio_l_organis_641b49_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                check=models.Q(("rent_amount_cents__gt", 0)), name="lease_rent_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                check=models.Q(("bond_amount_cents__gte", 0)),
                name="lease_bond_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["organisation", "name"], name="portfolio_t_organis_4513a4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenancy",
            constraint=models.UniqueConstraint(
                fields=("organisation", "reference"), name="uniq_tenancy_reference"
            ),
        ),
    ]
