# Generated by Django 5.0.14 on 2026-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="management_fee_bps",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Agency management fee in basis points of rent collected (e.g. 770 = 7.7%).",
            ),
        ),
    ]
