# Generated by Django 5.0.14 on 2026-08-24 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrearsCase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("monitoring", "Monitoring"),
                            ("overdue", "Overdue"),
                            ("escalated", "Escalated"),
                            ("notice_pending", "Notice pending (human action)"),
                            ("resolved", "Resolved"),
                        ],
                        default="overdue",
                        max_length=32,
                    ),
                ),
                ("days_overdue", models.IntegerField(default=0)),
                ("amount_owing_cents", models.BigIntegerField(default=0)),
                ("opened_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrears_cases",
                        to="portfolio.tenancy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("rent_received", "Rent received"),
                            ("payment_dishonoured", "Payment dishonoured"),
                            ("rent_overdue", "Rent overdue (scheduled check)"),
                        ],
                        max_length=64,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=8
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_approval",
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="automation.automationrule",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="portfolio.tenancy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="email",
                        max_length=8,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpsTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="automation.automationrule",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="portfolio.tenancy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("rent_received", "Rent received"),
                            ("payment_dishonoured", "Payment dishonoured"),
                            ("lease_activated", "Lease activated"),
                            ("arrears_threshold", "Arrears threshold crossed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleFiring",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dedup_key", models.CharField(max_length=255)),
                ("fired_at", models.DateTimeField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firings",
                        to="automation.automationrule",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.tenancy",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="arrearscase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "resolved"), _negated=True),
                fields=("tenancy",),
                name="uniq_open_arrears_case_per_tenancy",
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["organisation", "status"], name="automation__organis_ada33c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationtemplate",
            constraint=models.UniqueConstraint(
                fields=("organisation", "name"), name="uniq_template_name"
            ),
        ),
        migrations.AddIndex(
            model_name="opstask",
            index=models.Index(
                fields=["organisation", "status"], name="automation__organis_d52a09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                condition=models.Q(("processed_at__isnull", True)),
                fields=["organisation", "occurred_at"],
                name="outbox_unprocessed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulefiring",
            constraint=models.UniqueConstraint(
                fields=("rule", "tenancy", "dedup_key"), name="uniq_rule_firing"
            ),
        ),
    ]
