# Generated by Django 5.0.14 on 2026-08-24 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("trust_bank", "Trust bank account"),
                            ("tenancy_ledger", "Tenancy sub-ledger"),
                            ("owner_ledger", "Owner sub-ledger"),
                            ("agency_fees", "Agency fees clearing"),
                            ("bond_clearing", "Bond clearing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_account",
                        to="portfolio.owner",
                    ),
                ),
                (
                    "tenancy",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_account",
                        to="portfolio.tenancy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=512)),
                ("posted_at", models.DateTimeField()),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "journal entries",
            },
        ),
        migrations.CreateModel(
            name="Posting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                ("amount_cents", models.BigIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrustAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bsb", models.CharField(blank=True, max_length=7)),
                ("account_number", models.CharField(blank=True, max_length=32)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cutoff_date", models.DateField()),
                ("bank_balance_cents", models.BigIntegerField()),
                ("cashbook_balance_cents", models.BigIntegerField()),
                ("subledger_total_cents", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced"),
                            ("out_of_balance", "Out of balance"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="ledger.trustaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("next_number", models.BigIntegerField(default=1)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "trust_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_sequence",
                        to="ledger.trustaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.BigIntegerField()),
                ("amount_cents", models.BigIntegerField()),
                ("received_from", models.CharField(max_length=255)),
                ("method", models.CharField(default="eft", max_length=32)),
                ("issued_at", models.DateTimeField()),
                (
                    "journal_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="ledger.trustaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "amount_cents",
                    models.BigIntegerField(
                        help_text="Signed: positive = money in, negative = out."
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=512)),
                ("external_ref", models.CharField(max_length=255)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "matched_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_matches",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_transactions",
                        to="ledger.trustaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="trust_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="ledger.trustaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["organisation", "posted_at"],
                name="ledger_jour_organis_65e8dc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("organisation", "external_id"),
                name="uniq_entry_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="posting",
            index=models.Index(
                fields=["organisation", "account"],
                name="ledger_post_organis_a6d378_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="posting",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_cents__gt", 0)), name="posting_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliation",
            constraint=models.UniqueConstraint(
                fields=("trust_account", "cutoff_date"),
                name="uniq_reconciliation_cutoff",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["organisation", "trust_account", "number"],
                name="ledger_rece_organis_ceb3bb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("trust_account", "number"),
                name="uniq_receipt_number_per_trust_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_cents__gt", 0)), name="receipt_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["organisation", "trust_account", "date"],
                name="ledger_bank_organis_665e7a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("trust_account", "external_ref"),
                name="uniq_bank_txn_external_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organisation", "subtype"],
                name="ledger_acco_organis_8f13a8_idx",
            ),
        ),
    ]
