# Generated by Django 5.0.14 on 2026-08-24 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("NSW", "New South Wales"),
                            ("VIC", "Victoria"),
                            ("QLD", "Queensland"),
                            ("WA", "Western Australia"),
                            ("SA", "South Australia"),
                            ("TAS", "Tasmania"),
                            ("ACT", "Australian Capital Territory"),
                            ("NT", "Northern Territory"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("bond_authority", "Bond lodgement authority"),
                            ("bond_max", "Maximum bond"),
                            ("bond_lodgement_deadline", "Bond lodgement deadline"),
                            ("rent_increase_notice", "Rent increase minimum notice"),
                            (
                                "rent_increase_frequency",
                                "Rent increase frequency limit",
                            ),
                            ("trust_audit", "Trust account audit period/deadline"),
                            (
                                "no_grounds_termination",
                                "No-grounds termination permitted",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "config",
                    models.JSONField(
                        help_text="Rule payload, shape depends on rule_type (see compliance.services)."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Citation for the rule (act/regulator page).",
                        max_length=512,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="False until confirmed against the regulator (research figures are secondary sources).",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["jurisdiction", "rule_type", "effective_from"],
                        name="compliance__jurisdi_2b8d6b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="compliancerule",
            constraint=models.UniqueConstraint(
                fields=("jurisdiction", "rule_type", "effective_from"),
                name="uniq_rule_version",
            ),
        ),
    ]
