# Generated by Django 5.0.14 on 2026-08-25 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("compliance", "0002_seed_rules"),
        ("ledger", "0002_integrity_triggers"),
        ("portfolio", "0002_property_management_fee_bps"),
    ]

    operations = [
        migrations.CreateModel(
            name="BondLodgement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_cents", models.BigIntegerField()),
                ("jurisdiction", models.CharField(max_length=3)),
                ("authority_name", models.CharField(max_length=255)),
                ("held_in_agent_trust", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_receipt", "Pending receipt"),
                            ("received", "Received into trust"),
                            ("held_in_trust", "Held in agent trust (NT)"),
                            ("lodged", "Lodged with authority"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_receipt",
                        max_length=32,
                    ),
                ),
                ("received_on", models.DateField(blank=True, null=True)),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Statutory lodgement deadline; blank where none applies (NT).",
                        null=True,
                    ),
                ),
                ("authority_reference", models.CharField(blank=True, max_length=128)),
                ("lodged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bond_lodgement",
                        to="portfolio.lease",
                    ),
                ),
                (
                    "lodgement_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "receipt_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.trustaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organisation", "state"],
                        name="compliance__organis_a136ed_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bondlodgement",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_cents__gt", 0)), name="bond_amount_positive"
            ),
        ),
    ]
